apiVersion: v1
kind: ConfigMap
metadata:
  name: db-script
data:
# we can aslo create db , By passing MYSQL_DATABASE env to the mysql deployment https://hub.docker.com/_/mysql
  db_config.sql: |-
    CREATE DATABASE mydb; 
    USE mydb;
    CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) NOT NULL,email VARCHAR(50) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

