apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: DB_PASSWORD
        volumeMounts:
        - name: mystorage
          mountPath: /var/lib/mysql
        - name: db-config-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mystorage
          persistentVolumeClaim:
            claimName: mystorage
        - name: db-config-script
          configMap:
            name: db-script
      
